services:
  - type: web
    name: laravel-app
    env: docker
    repo: https://github.com/<ton-nom-utilisateur>/<ton-repo>
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      # Ajoute les autres variables ici
      
